# Resolve react_native_pods.rb with node to allow for hoisting
source 'https://cdn.cocoapods.org/'

# Set deployment target before requiring react-native-pods
$RN_DEPLOYMENT_TARGET = '14.0'
$RNFirebaseAsStaticFramework = true

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, $RN_DEPLOYMENT_TARGET
prepare_react_native_project!

use_frameworks! :linkage => :static

target 'TxyCo' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Explicitly specify DoubleConversion version
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false

  # Firebase dependencies
  pod 'Firebase', '~> 11.2.0'
  pod 'Firebase/Core', '~> 11.2.0'
  pod 'Firebase/Auth', '~> 11.2.0'
  pod 'Firebase/Database', '~> 11.2.0'
  
  # Maps dependencies
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'TxyCoTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Fix deployment target for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $RN_DEPLOYMENT_TARGET
      end
    end
  end
end
